sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.4.1
  - 2.5.0
before_install: >
  gem install bundler -v 1.15.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - rake ci
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
